FROM busybox
LABEL maintainer="todd <toddwunz@gmail.com>" app="httpd"
ENV WEB_ROOT="/data/web/html"
RUN mkdir -p ${WEB_ROOT} && \
    echo '<h1>Busybox httpd service test page.</h1>' > ${WEB_ROOT}/index.html

# CMD /bin/httpd -f -h ${WEB_ROOT}
# CMD ["/bin/httpd", "-f", "-h ${WEB_ROOT}"] 
# CMD ["/bin/sh", "-c", "/bin/httpd", "-f", "-h ${WEB_ROOT}"] 
ENTRYPOINT /bin/httpd -f -h ${WEB_ROOT}
